"""Render all Divine Printing product pages."""
import os, json

BASE = "/home/ubuntu/.openclaw/workspace/divineprinting"
OUT  = f"{BASE}/products"
os.makedirs(OUT, exist_ok=True)

# ─── Product data ────────────────────────────────────────────────────────────
P = [
  {"s":"church-vinyl-banner","img":"vinyl-banner.jpg","badge":"Best Seller","cat":"Banners & Flags","name":"Church Vinyl Banner","tag":"Heavy-duty outdoor banners crafted for your ministry — built to last through every season of service.","verse":"Therefore go and make disciples of all nations...","ref":"Matthew 28:19","specs":[("Material","510g PVC Vinyl"),("Print","UV / Eco-Solvent Ink, 1440 dpi"),("UV Resistance","Up to 5 years outdoors"),("Max Width","5 meters, unlimited length"),("Finishing","Double-sewn edges + metal grommets"),("Customization","Crosses, doves, scripture text")],"feats":["Cross, dove, and scripture design options available","Weatherproof — rain, sun, and wind resistant","Double-thread sewn edges for maximum durability","Metal grommets at all corners for secure hanging","Rush production available for Sunday deadlines"],"desc":["Church Vinyl Banners are one of our most popular products. Whether announcing a revival, welcoming visitors, promoting VBS, or sharing a scripture verse with your community, a well-designed vinyl banner is one of the most effective tools your ministry can have.","Our 510g premium vinyl offers the highest durability we carry. UV-cured ink ensures your banner stays vibrant for up to 5 years outdoors, even in direct sunlight. Each banner is finished with double-folded, double-thread sewn edges and metal grommets for secure mounting anywhere.","Every banner can be customized with religious imagery including crosses, doves, praying hands, and scripture text. Upload your own design or work with our team to create something that truly represents your congregation."],"uc":[("⛪","Sunday service announcements"),("📖","Scripture & message banners"),("🎉","VBS, revival & special events"),("🌟","Holiday & seasonal displays"),("🤝","Community outreach programs"),("🏫","Church school & youth ministry")],"sizes":["2×4 ft","3×6 ft","4×8 ft","4×10 ft","Custom"]},
  {"s":"mesh-banner","img":"mesh-banner.jpg","badge":"Outdoor","cat":"Banners & Flags","name":"Wind-Resistant Mesh Banner","tag":"Breathable mesh banners that stand up to wind — ideal for fences, outdoor stages, and revival tents.","verse":"The wind blows where it wishes, and you hear its sound...","ref":"John 3:8","specs":[("Material","300gsm / 380gsm Vinyl Mesh"),("Print","Eco-Solvent / UV Curing, 1440 dpi"),("UV Resistance","1–3 years"),("Wind Resistance","High — 30-40% open mesh"),("Finishing","Double-sewn edges + grommets"),("Application","Fences, scaffolding, outdoor stages")],"feats":["Perforated mesh allows airflow — will not act as a sail","Perfect for chain-link fences at church events","Full-color religious designs at high resolution","Available in 300gsm and 380gsm weights","Metal grommets at regular intervals for secure tie-down"],"desc":["Mesh banners are the smart choice when you need outdoor signage in windy conditions. Unlike solid vinyl, the open mesh structure lets wind pass through — preventing the banner from acting as a sail and reducing stress on mounting points.","Ideal for hanging on chain-link fences around your church property, along scaffolding, at outdoor events, or on the perimeter of revival tents. The perforated material still provides bold, clear visuals from a distance.","We offer 300gsm for lighter-duty applications and 380gsm for more permanent installations. All mesh banners include metal grommets and double-sewn edges as standard."],"uc":[("⛺","Revival tent perimeter signage"),("🏗️","Scaffolding & construction wraps"),("🏟️","Event fencing & barriers"),("🌬️","High-wind outdoor locations"),("🤝","Community outreach events"),("⛪","Church parking lot displays")],"sizes":["3×6 ft","4×8 ft","4×20 ft","Custom"]},
  {"s":"fabric-sanctuary-banner","img":"fabric-banner.jpg","badge":"Indoor","cat":"Banners & Flags","name":"Fabric Sanctuary Banner","tag":"Elegant indoor fabric banners that bring warmth and reverence to your worship space.","verse":"Praise Him in His sanctuary; praise Him in His mighty heavens.","ref":"Psalm 150:1","specs":[("Material","250gsm Polyester Fabric"),("Print","Thermal Sublimation, 1440 dpi"),("UV Resistance","3–6 months indoor"),("Finish","Soft fabric — no glare"),("Hanging","Rod pocket or grommets"),("Customization","Cross, dove, flame, stained-glass")],"feats":["Soft fabric feel — elegant and dignified for sanctuaries","No light glare — perfect for photography and video","Vibrant thermal sublimation printing","Cross, dove, flame, and stained-glass design options","Lightweight and portable — ideal for traveling ministries"],"desc":["Fabric Sanctuary Banners bring a different kind of presence to your worship space. Unlike vinyl, fabric has a soft, dignified look that suits the reverence of a sanctuary. These banners drape beautifully and photograph well without any glare.","Using thermal sublimation printing, we achieve vibrant full-color imagery that becomes part of the fabric itself — it will not peel, crack, or fade under normal indoor conditions.","Popular designs include crosses with rays of light, descending doves, flames representing the Holy Spirit, stained-glass patterns, and scripture passages in elegant typography."],"uc":[("⛪","Behind the pulpit / altar area"),("🕊️","Sanctuary wall décor"),("📸","Photography-friendly backdrops"),("🎄","Seasonal worship decorations"),("✈️","Traveling & mobile ministries"),("🎭","Baptism & ceremony backdrops")],"sizes":["2×4 ft","2×6 ft","3×6 ft","4×8 ft","Custom"]},
  {"s":"custom-ministry-flag","img":"flag.jpg","badge":"Custom","cat":"Banners & Flags","name":"Custom Ministry Flag","tag":"Fly your faith — custom flags for churches, ministries, and congregations.","verse":"As for me and my house, we will serve the Lord.","ref":"Joshua 24:15","specs":[("Material","75D or 100D Polyester"),("Standard Size","3×5 ft"),("Print","Full-color, single or double-sided"),("UV Resistance","Outdoor-rated ink"),("Header","Canvas header with brass grommets"),("Customization","Logo, cross, ministry crest")],"feats":["Feature your church logo, cross, or ministry crest","Available in standard 3×5ft or any custom size","Durable polyester for outdoor use in all weather","Double-sided printing available with center liner","Canvas header with brass grommets for pole mounting"],"desc":["A custom ministry flag is one of the most visible statements of identity your church can make. Whether flown from a pole outside your building, carried in a processional, or used at outdoor crusades, a flag bearing your church emblem broadcasts your mission with dignity.","We print on 75D or 100D polyester — a durable, weather-resistant fabric that holds color well and flies cleanly in the wind. Standard size is 3×5ft to fit most flagpoles, but we can produce any size you need.","For ministries that want visibility from both sides — such as processional or event flags — we offer double-sided printing with a center liner to prevent show-through."],"uc":[("🏛️","Flagpole outside church"),("🎺","Processional & worship flags"),("⛺","Outdoor crusades & revivals"),("🏅","Ministry events & conferences"),("🏫","Christian schools & academies"),("🌍","Mission trip representation")],"sizes":["3×5 ft (standard)","4×6 ft","5×8 ft","Custom"]},
  {"s":"feather-teardrop-flag","img":"feather-flag.jpg","badge":"Event Favorite","cat":"Banners & Flags","name":"Feather & Teardrop Flag","tag":"Eye-catching swooper flags that draw crowds to your outdoor ministry events.","verse":"Stand firm, then, and do not let yourselves be burdened again.","ref":"Galatians 5:1","specs":[("Shapes","Feather, Teardrop, Rectangular"),("Heights","2.8m, 3.4m, 4m, 4.5m, 5m, 5.5m"),("Material","Polyester Fabric"),("Print","Full-color, single or double-sided"),("Base Options","Ground spike, Cross base, Water base"),("Pole","Fiberglass — included")],"feats":["6 height options from 2.8m to 5.5m tall","Feather, teardrop, and rectangular shape choices","Ground spike for outdoor grass installation","Cross base available for indoor or hard surface use","Vivid full-color printing with your church design"],"desc":["Feather and teardrop flags are designed to be noticed. Their distinctive curved shapes create movement in even the lightest breeze, drawing the eye from a distance and signaling to passersby that something is happening at your location.","Perfect for outdoor events — place them along the sidewalk before a revival, flank your ministry tent at a festival, or line the entrance to your church for special services. Available in heights up to 5.5 meters.","Each flag comes with a fiberglass pole and your choice of base: a ground spike for installation in grass, or a cross base for indoor and hard surface use. No tools needed for assembly."],"uc":[("🎪","Event & festival entrances"),("⛺","Revival & crusade perimeter"),("🛒","Sidewalk & parking lot draws"),("🏟️","Sports ministry events"),("🎄","Holiday & seasonal services"),("📢","Community outreach attention")],"sizes":["2.8m","3.4m","4.0m","4.5m","5.0m","5.5m"]},
  {"s":"retractable-rollup-banner","img":"rollup-banner.jpg","badge":"Same-Day Available","cat":"Event Displays","name":"Retractable Roll-Up Banner","tag":"Professional retractable banners for church lobbies, stages, and events.","verse":"For God so loved the world that He gave His one and only Son...","ref":"John 3:16","specs":[("Width Options","80cm or 85cm"),("Height","200cm"),("Frame","Aluminum alloy — Economy & Luxury"),("Material","Polyester banner"),("Production","Same-day available"),("Includes","Carry bag")],"feats":["Pulls out and retracts in seconds — no tools needed","Economy and luxury aluminum stand options","Sermon series, welcome, and scripture designs available","Same-day production on select orders","Includes protective carry bag for easy transport"],"desc":["Retractable roll-up banners are the workhorses of church interior signage. Set one up in your lobby to welcome first-time visitors. Place two flanking the stage to frame your sermon series artwork. Use them at registration tables for conferences or VBS.","The beauty of roll-up banners is their speed — pull up, lock in, done in under 30 seconds. They retract just as fast and stow in a slim carry bag, ideal for multi-use spaces and traveling ministries.","We offer 80cm and 85cm widths, both at 200cm height. Choose from economy or luxury aluminum stands. Same-day production is available because we know Sunday does not wait."],"uc":[("🏛️","Church lobby welcome displays"),("🎤","Stage & pulpit flanking"),("📋","Registration & check-in tables"),("📅","Sermon series promotions"),("🎓","Conference & summit signage"),("🎄","Seasonal event displays")],"sizes":["80cm × 200cm","85cm × 200cm"]},
  {"s":"stage-backdrop-banner","img":"backdrop.jpg","badge":"Event Fave","cat":"Event Displays","name":"Stage Backdrop Banner","tag":"Large-format fabric backdrops that transform your stage for any ministry event.","verse":"One thing I ask from the Lord... to dwell in the house of the Lord all the days of my life.","ref":"Psalm 27:4","specs":[("Material","Polyester Fabric"),("Frame","Aluminum alloy pop-up"),("Standard Sizes","8×8 ft up to 10×20 ft"),("Print","Full-color, vibrant"),("Setup","Tool-free, under 5 minutes"),("Includes","Heavy-duty carry bag")],"feats":["Photo-perfect print quality for video and photography","No wrinkles — fabric stretches taut over aluminum frame","Pop-up frame sets up in minutes without tools","Perfect for baptisms, weddings, and holiday services","Sizes up to 10×20ft for large stages"],"desc":["A stage backdrop banner instantly elevates the look of any event. Whether hosting a baptism, Christmas production, wedding ceremony, or multi-day conference, the backdrop appears in every photo and video frame — it should look intentional.","Our backdrop banners are printed on smooth polyester fabric and mounted on an aluminum pop-up frame that sets up in minutes without tools. The fabric pulls taut to eliminate wrinkles, giving you a clean, professional surface.","Available from 8×8ft up to 10×20ft to fill any stage. Bring your custom design — sermon series artwork, church branding, scripture passages, or seasonal imagery — and we will print it in full color."],"uc":[("💧","Baptism ceremony backdrops"),("💒","Wedding & ceremony décor"),("🎄","Christmas & Easter productions"),("📸","Photo booth & media wall"),("🎤","Conference & summit staging"),("📺","Live stream backgrounds")],"sizes":["8×8 ft","8×10 ft","10×10 ft","10×15 ft","10×20 ft"]},
  {"s":"ministry-canopy-tent","img":"canopy-tent.jpg","badge":"Popular","cat":"Event Displays","name":"Ministry Canopy Tent","tag":"Custom branded canopy tents for outdoor outreach, fairs, and community events.","verse":"The glory of the Lord filled the tabernacle.","ref":"Exodus 40:34","specs":[("Sizes","10×10 ft, 10×15 ft, 10×20 ft"),("Frame","Heavy-duty aluminum alloy"),("Canopy Material","Polyester, full-color print"),("Setup","Tool-free pop-up"),("Sidewalls","Removable, optional"),("Includes","Carry bag + ground stakes")],"feats":["Print your church name, logo, and branding on all panels","Sturdy aluminum frame stands up in outdoor conditions","Three size options for any event scale","Full-color printing on roof, valances, and sidewalls","Removable sidewalls for versatile configurations"],"desc":["A branded canopy tent is your ministry mobile billboard. Whether at a community fair, block party, farmers market, or public outreach event, your tent is the first thing people see — and a fully branded tent tells them exactly who you are before you say a word.","Our aluminum-framed canopy tents are built for repeated outdoor use. The pop-up frame sets up quickly and holds firm in typical outdoor conditions. The polyester canopy and optional sidewalls can be printed in full color.","Three sizes are available — 10×10ft for small presences, up to 10×20ft giving you a full command post for larger events with room for tables, chairs, and ministry materials."],"uc":[("🏘️","Community fairs & festivals"),("🤝","Street outreach events"),("🌾","Farmers markets & expos"),("🏃","Sports & recreation events"),("🍽️","Church picnics & cookouts"),("📋","Charity drives & fundraisers")],"sizes":["10×10 ft","10×15 ft","10×20 ft"]},
  {"s":"a-frame-popup-banner","img":"popup-banner.jpg","badge":"Portable","cat":"Event Displays","name":"A-Frame Pop-Up Banner","tag":"Portable, attention-grabbing pop-up banners for lobbies, tables, and event spaces.","verse":"Go into all the world and preach the gospel to all creation.","ref":"Mark 16:15","specs":[("Shapes","Oval, Teardrop, Bean, Round"),("Frame Material","Fiberglass — lightweight"),("Banner Material","Polyester fabric"),("Print","Full-color both sides available"),("Assembly","Tool-free, under 60 seconds"),("Portability","Includes carry bag")],"feats":["Four shape options: oval, teardrop, bean-shaped, round","Lightweight fiberglass frame — easy to carry anywhere","Full-color printing in your church branding","Doubles as table display or freestanding banner","Assembles in under a minute without any tools"],"desc":["A-Frame pop-up banners offer maximum visual impact with minimum setup time. Their unique curved shapes — oval, teardrop, bean, and round — stand out from rectangular banners that crowd most event spaces, drawing the eye naturally.","Ideal for placing near tables at church events, flanking a registration desk, marking a welcoming area in your lobby, or guiding visitors at conferences. Their lightweight fiberglass frame makes them easy to carry and position anywhere.","Each banner comes with a carry bag for storage and transport, making them a great investment for ministries that run regular events or outreach programs."],"uc":[("🏛️","Lobby welcome & wayfinding"),("📋","Registration & info tables"),("🎤","Speaker introductions"),("🎪","Event booth identification"),("🏫","Church school & classrooms"),("🌍","Conference & summit displays")],"sizes":["Small (2.8m)","Medium (3.4m)","Large (4m)","Custom"]},
  {"s":"church-yard-sign","img":"yard-sign.jpg","badge":"New","cat":"Signs & Signage","name":"Church Yard Sign","tag":"Weatherproof corrugated plastic yard signs for service times, events, and outreach.","verse":"He has anointed me to proclaim good news to the poor.","ref":"Luke 4:18","specs":[("Material","4.5mm Corrugated Plastic (Coroplast)"),("Weight","1100gsm"),("UV Resistance","12 months outdoors"),("Shape","Custom cut available"),("Hardware","Wire H-stake or frame"),("Sides","Single or double-sided")],"feats":["Weatherproof — stands up to rain, heat, and cold","12-month UV resistance keeps colors vibrant outdoors","Custom cut shapes — arrows, crosses, and more","Wire H-stake included for easy lawn installation","Lightweight and reusable season after season"],"desc":["Church yard signs are one of the most cost-effective ways to communicate with your surrounding community. Place them along the street before a special service, along walkways to guide visitors, or in congregation members yards to spread the word.","Made from 4.5mm thick corrugated plastic (Coroplast), these signs are weatherproof and lightweight. Wire H-stakes push directly into the ground — no tools required. UV-resistant printing keeps your design sharp for up to 12 months outdoors.","We offer custom cut shapes alongside standard rectangles — cross-shaped signs and directional arrows are popular choices for churches. Full-color print is available on one or both sides."],"uc":[("📢","Street-side service announcements"),("🎉","VBS and event promotion"),("🤝","Community outreach programs"),("🎄","Holiday service notifications"),("📍","Directional signage for events"),("🏘️","Member lawn displays")],"sizes":["12×18 in","18×24 in","24×36 in","Custom"]},
  {"s":"acrylic-pvc-sign","img":"acrylic-sign.jpg","badge":"Premium","cat":"Signs & Signage","name":"Acrylic & PVC Sign","tag":"Rigid, professional-grade signs for permanent church interior and exterior use.","verse":"Trust in the Lord with all your heart and lean not on your own understanding.","ref":"Proverbs 3:5","specs":[("Materials","PVC or Acrylic"),("Thickness","2mm – 20mm"),("Print Method","UV printing — ink bonded to surface"),("Shape","Any custom shape"),("Finish","Gloss or matte"),("Mounting","Standoffs, adhesive, or screws")],"feats":["Premium UV printing directly onto rigid material","PVC (budget) or Acrylic (premium clarity) options","Custom shapes — crosses, shields, arches, and more","Thickness from 2mm to 20mm for any application","Professional standoff mounting hardware available"],"desc":["Acrylic and PVC signs bring a level of permanence and professionalism that fabric and paper simply cannot match. These are the signs you install once and leave — on walls, doors, welcome desks, hallways, and exterior facades.","We print directly onto the rigid material using UV printing, which bonds ink permanently to the surface. PVC is our budget-friendly option for most indoor applications. Acrylic offers premium glass-like clarity for lobby nameplates and decorative wall pieces.","Both materials can be cut to custom shapes. Cross-shaped plaques, shield crests, arched nameplates, and directional signs are all achievable. Thickness ranges from 2mm to 20mm."],"uc":[("🏛️","Church name & address plaques"),("🚪","Room & ministry labels"),("🤝","Welcome desk nameplates"),("📍","Directional & wayfinding signs"),("🏆","Memorial & honor plaques"),("📸","Decorative scripture wall art")],"sizes":["Custom — any size from 4×4 in to 4×8 ft"]},
  {"s":"church-vinyl-sticker","img":"sticker.jpg","badge":"Giveaway Favorite","cat":"Stickers & Magnets","name":"Church Vinyl Sticker","tag":"Custom die-cut stickers with crosses, scripture, and church logos — perfect for outreach and giveaways.","verse":"In all things God works for the good of those who love Him.","ref":"Romans 8:28","specs":[("Material","UV-resistant vinyl"),("Print","Full-color"),("Cut","Custom die-cut or standard"),("Finish","Gloss or matte"),("Application","Indoor & outdoor surfaces"),("Min. Order","25 units")],"feats":["Custom die-cut to any shape — crosses, doves, shields","UV-resistant — suitable for outdoor surfaces","Full-color printing for vibrant religious designs","Great for bulk giveaways at events and outreach","Apply to Bibles, laptops, water bottles, car bumpers"],"desc":["Vinyl stickers are one of the most versatile and affordable outreach tools available. A well-designed sticker with your church logo, a memorable scripture, or a bold cross graphic becomes a mini billboard wherever it is placed.","Our stickers are printed in full color on durable UV-resistant vinyl. Custom die-cutting lets us produce any shape — a traditional cross, a descending dove, a shield, a fish symbol, or your church emblem.","Stickers are extremely popular as giveaways at VBS, youth events, revivals, and community outreach programs. They are inexpensive enough to give away freely and impactful enough to leave a lasting impression."],"uc":[("🎁","Event & VBS giveaways"),("📖","Bible & journal decoration"),("🚗","Car bumper & window stickers"),("💻","Laptop & device stickers"),("🤝","Outreach kits & welcome bags"),("🏫","Youth group merchandise")],"sizes":["1×1 in","2×2 in","3×3 in","4×4 in","Custom"]},
  {"s":"window-transfer-decal","img":"window-decal.jpg","badge":"Clean Look","cat":"Stickers & Magnets","name":"Window Transfer Decal","tag":"Letter-only window decals that give your church a clean, professional storefront presence.","verse":"Whatever you do, do it all in the name of the Lord Jesus.","ref":"Colossians 3:17","specs":[("Type","Transfer vinyl — no background"),("Thickness","100 microns"),("UV Resistance","3–5 years"),("Application","Glass, windows, smooth surfaces"),("Size","Custom"),("Removal","Clean, no residue")],"feats":["Letters and shapes only — no background film visible","Applied directly to glass for a professional look","UV resistant for 3–5 years outdoors","Perfect for church name, service times, and scripture","Available in any color — gold and white are popular"],"desc":["Transfer decals give your church windows and glass doors a clean, permanent-looking display without the boxed-in appearance of a standard sticker. Because there is no background film — just the lettering and graphics themselves — the result looks like text is printed directly on the glass.","Ideal for displaying your church name and address on the front door, listing service times, applying scripture to a glass partition, or labeling ministry rooms with elegant vinyl lettering.","At 100 microns thick, our transfer decals are durable enough for outdoor glass while remaining cleanly removable if your messaging ever needs to change."],"uc":[("🚪","Front door & entrance glass"),("🕐","Service times display"),("📖","Scripture on glass partitions"),("🏛️","Church name & address"),("🏢","Office & ministry room labels"),("🪟","Storefront & lobby windows")],"sizes":["Custom — any size"]},
  {"s":"floor-decal","img":"floor-sticker.jpg","badge":"Durable","cat":"Stickers & Magnets","name":"Floor Decal","tag":"Waterproof, slip-resistant floor graphics that guide and inspire your congregation.","verse":"Make level paths for your feet and take only ways that are firm.","ref":"Proverbs 4:26","specs":[("Material","Vinyl with anti-slip laminate"),("UV Resistance","Yes"),("Waterproof","Yes"),("Abrasion Resistance","High — foot traffic rated"),("Size","Any size"),("Shape","Any shape")],"feats":["Anti-slip surface laminate for safety compliance","Waterproof — suitable for entryways and outdoor areas","High abrasion resistance — built for foot traffic","Full-color printing in any design","Custom shapes including crosses, circles, and arrows"],"desc":["Floor decals are an often-overlooked but highly effective form of church signage. Placed at key decision points throughout your facility, floor graphics guide visitors intuitively toward the sanctuary, restrooms, children's ministry, or welcome desk.","Beyond wayfinding, floor decals can be used creatively — a scripture verse greeting visitors at the entrance, a cross motif in the lobby, or dove-styled directional arrows leading families to the children's area.","Our floor decals include an anti-slip laminate layer for safety. They are waterproof and abrasion-resistant, suitable for entryways and interior spaces alike. Any size and shape is available."],"uc":[("🧭","Wayfinding & directional arrows"),("✝️","Decorative cross motifs"),("📖","Scripture verse displays"),("🏛️","Lobby welcome graphics"),("👶","Children's area markers"),("🤸","Youth & recreation spaces")],"sizes":["Custom — any size and shape"]},
  {"s":"church-fridge-magnet","img":"magnet.jpg","badge":"Giveaway","cat":"Stickers & Magnets","name":"Church Fridge Magnet","tag":"Custom fridge magnets with service info, prayer guides, and church contact details.","verse":"I can do all this through Him who gives me strength.","ref":"Philippians 4:13","specs":[("Thickness","0.3mm / 0.5mm / 0.7mm / 0.9mm"),("Shape","Any shape"),("Print","Full-color"),("Feature","Removable & writable surface"),("Size","Custom"),("Min. Order","50 units")],"feats":["Full-color printing of your church branding and info","Service times, address, and phone on one piece","Writable surface — members can add personal notes","Four thickness options from 0.3mm to 0.9mm","Custom cut to any shape — cross, shield, or house"],"desc":["Church refrigerator magnets are a classic and practical giveaway. Every time a congregation member opens their fridge, they see your church name, service times, phone number, and whatever message you choose to include.","Popular designs include weekly scripture verses, prayer request phone lines, service schedule cards, and holiday greetings. The writable surface allows members to jot notes directly on the magnet — making them interactive beyond just branding.","Available in four thickness options. Custom cut shapes — a cross, a church building silhouette, or a simple rectangle — add a distinctive touch that sets your magnets apart from the generic."],"uc":[("🎁","New member welcome kits"),("📅","Service schedule reminders"),("🙏","Prayer guide giveaways"),("🎄","Christmas & holiday gifts"),("📞","Church contact info cards"),("🏘️","Community outreach packages")],"sizes":["Business card size","4×6 in","Custom"]},
  {"s":"magnetic-car-sign","img":"car-magnet.jpg","badge":"Mobile Ministry","cat":"Stickers & Magnets","name":"Magnetic Car Sign","tag":"Removable magnetic signs for church vehicles — spread your ministry message on every road.","verse":"How beautiful are the feet of those who bring good news!","ref":"Romans 10:15","specs":[("Thickness","0.5mm / 0.7mm / 0.9mm"),("Print","Full-color"),("Shape","Any shape"),("UV Resistance","Yes"),("Waterproof","Yes"),("Removable","Yes — no adhesive residue")],"feats":["Removable and reusable — no adhesive residue ever","UV-resistant and waterproof for outdoor use","Full-color print of your church logo and message","Holds firmly to any magnetic metal vehicle surface","Easy to swap between vehicles as needed"],"desc":["Magnetic car signs turn your personal or church vehicle into a moving advertisement for your ministry. Every drive across town is an opportunity for your congregation to represent your church in the community — and for curious passersby to learn who you are.","Unlike vinyl decals, magnetic signs are fully removable and leave zero residue. A church member can promote the ministry during the week and remove the sign for personal use on weekends. They are also interchangeable between vehicles.","Our magnets are UV-resistant and fully waterproof, handling daily driving conditions without fading or deteriorating."],"uc":[("🚗","Personal member vehicles"),("🚐","Church van & bus fleet"),("🤝","Community event promotion"),("📢","Revival & event announcements"),("🌍","Mission trip vehicles"),("🏘️","Neighborhood outreach")],"sizes":["12×18 in","18×24 in","Custom"]},
  {"s":"car-van-wrap","img":"vehicle-wrap.jpg","badge":"High Impact","cat":"Stickers & Magnets","name":"Car / Van Wrap","tag":"Full and partial vehicle wraps that transform your church vehicle into a rolling ministry.","verse":"You will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.","ref":"Acts 1:8","specs":[("Material","140gsm Cast Vinyl"),("Print Method","Eco / UV Ink"),("UV Resistance","3–5 years"),("Coverage","Full or partial wrap"),("Finish","Gloss or matte"),("Application","Professional installation recommended")],"feats":["3–5 year UV resistance — built for long-term use","Full or partial wrap options to fit any budget","140gsm cast vinyl conforms to vehicle curves perfectly","Bold full-color church branding and scripture","Protects original paint — removes cleanly when needed"],"desc":["A vehicle wrap is the highest-impact mobile advertising available. Studies show a wrapped vehicle generates 30,000–70,000 impressions per day in urban environments. For a church van, pastor's car, or ministry vehicle, that is an extraordinary daily reach for your ministry.","Our 140gsm cast vinyl wraps are designed to conform to the contours of any vehicle without bubbles or lifting. The material is UV-resistant for 3–5 years, and when it is time for a change, the vinyl removes cleanly without damaging the original paint.","Full wraps cover the entire vehicle. Partial wraps — covering just the doors, rear, or one side panel — still deliver strong visual impact at a more accessible cost."],"uc":[("🚐","Church van & shuttle fleet"),("🚗","Pastor's personal vehicle"),("🚌","Youth ministry bus"),("🏘️","Community visibility & branding"),("🌍","Mission trip vehicles"),("📢","Event announcement vehicles")],"sizes":["Full wrap","Half wrap","Partial (doors / rear)","Custom"]},
  {"s":"church-tablecloth","img":"tablecloth.jpg","badge":"Event Essential","cat":"Event Displays","name":"Church Tablecloth","tag":"Custom full-color tablecloths that brand your tables at every church event.","verse":"You prepare a table before me in the presence of my enemies","ref":"Psalm 23:5","specs":[("Material","Polyester"),("Print","Full-color, all-over"),("Size","Custom — fits 6ft & 8ft tables"),("Style","Fitted or draped"),("Care","Machine washable"),("Color","Any color")],"feats":["Full-color printing across the entire cloth","Available in fitted and draped styles","Machine washable and reusable for multiple events","Custom any color to match your church branding","Fits standard 6ft and 8ft event tables"],"desc":["A custom tablecloth is one of those finishing touches that takes a church event from ordinary to polished. Whether it is a welcome table, a merch booth, a registration desk, or a fellowship dinner — a tablecloth printed with your church name, logo, and colors ties the whole setup together visually.","Our tablecloths are made from high-quality polyester and printed in full color across the entire surface. Choose a fitted style that wraps neatly around the table legs, or a draped style that flows elegantly to the floor. Both are machine washable and can be reused across many events.","Popular configurations include a large church name and cross on the front panel, with contact info and a scripture verse on the sides — especially popular for community events, ministry booths, and conference tables."],"uc":[("🍽️","Fellowship dinners & banquets"),("📋","Registration & welcome tables"),("🎪","Event & fair ministry booths"),("🏆","Award & recognition events"),("🎓","Conference & summit tables"),("🤝","Community outreach tables")],"sizes":["6 ft table","8 ft table","Custom"]},
  {"s":"church-flyer-bulletin","img":"flyer.jpg","badge":"Church Staple","cat":"Print & Paper","name":"Church Flyer & Bulletin","tag":"Full-color church bulletins, event flyers, and service programs on premium paper.","verse":"Preach the word; be prepared in season and out of season.","ref":"2 Timothy 4:2","specs":[("Sizes","A5, A4, A3, Custom"),("Paper Weights","120g, 157g, 180g, 200g, 250g"),("Print","Full-color, both sides"),("Finish","Gloss or matte"),("Turnaround","Same-day available"),("Min. Order","25 units")],"feats":["Five paper weight options from 120g to 250g","Full-color printing on both sides","Available in A5, A4, and A3 sizes","Gloss finish for bold photography and vibrant color","Same-day production available for Sunday emergencies"],"desc":["The church bulletin is one of the most enduring forms of church communication — and a well-designed one makes a real difference in how your congregation experiences a service. From the order of worship and upcoming events to announcements and prayer requests, the bulletin ties a service together.","Beyond weekly bulletins, we produce event flyers for revivals, concerts, VBS, community outreach programs, and church anniversaries. Our five paper weight options let you choose between an everyday 120g sheet for weekly bulletins and a premium 250g card stock for special occasion programs.","All orders are printed in full color on both sides. Same-day production is available — because we understand that church is Sunday and deadlines are real."],"uc":[("📋","Weekly service bulletins"),("🎉","Event flyers & invitations"),("📅","Ministry calendars"),("🙏","Prayer & devotional cards"),("🎭","Service & ceremony programs"),("📢","Community outreach flyers")],"sizes":["A5 (5.8x8.3 in)","A4 (8.3x11.7 in)","A3 (11.7x16.5 in)","Custom"]},
]

# ─── HTML renderer ───────────────────────────────────────────────────────────
TOPBAR = '<div class="topbar"><span>✝ Free shipping on orders over $150</span><span>|</span><span>📞 <a href="tel:+18005551234">1-800-DIVINE-1</a></span><span>|</span><span>⚡ Same-day production available</span></div>'

def nav(slug):
    return f'''<header><div class="nav-inner"><a href="../index.html" class="logo"><div class="logo-icon">✝</div><div class="logo-text"><div class="brand">Divine Printing</div><div class="tagline">Crafted for the Kingdom</div></div></a><nav><a href="../index.html">Home</a><a href="../index.html#banners">Banners &amp; Flags</a><a href="../index.html#events">Event Displays</a><a href="../index.html#signage">Signs</a><a href="../index.html#promo">Promo &amp; Stickers</a><a href="../index.html#print">Print</a><a href="#quote" class="nav-cta">Get a Quote →</a></nav></div></header>'''

FOOTER = '''<footer><div class="footer-inner"><div class="footer-brand"><div class="brand">✝ Divine Printing</div><p>Faith-inspired printing for churches, ministries &amp; congregations nationwide. Every product crafted with care and purpose.</p><div class="scripture">"Whatever you do, work at it with all your heart, as working for the Lord." — Colossians 3:23</div></div><div class="footer-col"><h4>Products</h4><a href="../index.html#banners">Church Banners</a><a href="../index.html#events">Event Displays</a><a href="../index.html#signage">Signs &amp; Signage</a><a href="../index.html#promo">Stickers &amp; Magnets</a><a href="../index.html#print">Flyers &amp; Bulletins</a></div><div class="footer-col"><h4>Company</h4><a href="#">About Us</a><a href="#">Ministry Discounts</a><a href="#">Design Templates</a><a href="#">Testimonials</a></div><div class="footer-col"><h4>Support</h4><a href="#quote">Get a Quote</a><a href="#">Shipping Info</a><a href="#">Returns</a><a href="#">FAQ</a></div></div><div class="footer-bottom"><span>© 2025 Divine Printing · divineprinting.com</span><span><a href="#">Privacy Policy</a> &nbsp;·&nbsp; <a href="#">Terms</a></span></div></footer>'''

def render(p):
    specs = "".join(f'<div class="spec-row"><span class="spec-label">{k}</span><span class="spec-value">{v}</span></div>' for k,v in p["specs"])
    feats = "".join(f"<li>{f}</li>" for f in p["feats"])
    desc  = "".join(f"<p>{d}</p>" for d in p["desc"])
    uc    = "".join(f'<div class="use-case-item"><span class="uc-icon">{e}</span>{t}</div>' for e,t in p["uc"])
    sizes = "".join(f'<option value="{s}">{s}</option>' for s in p["sizes"])
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <title>{p["name"]} — Divine Printing</title>
  <meta name="description" content="{p["tag"]}"/>
  <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
  <link rel="stylesheet" href="../styles.css"/>
  <link rel="stylesheet" href="../product.css"/>
</head>
<body>
{TOPBAR}
{nav(p["s"])}
<div class="breadcrumb"><div style="max-width:1280px;margin:0 auto;padding:0 24px;"><a href="../index.html">Home</a><span>›</span><a href="../index.html#products">{p["cat"]}</a><span>›</span>{p["name"]}</div></div>
<div class="product-hero">
  <div class="product-gallery">
    <div class="product-main-img"><img src="../images/{p["img"]}" alt="{p["name"]}"/><span class="img-badge">{p["badge"]}</span></div>
    <div class="product-scripture">"{p["verse"]}"<cite>— {p["ref"]}</cite></div>
  </div>
  <div class="product-info">
    <div class="pi-category">✝ {p["cat"]}</div>
    <h1>{p["name"]}</h1>
    <p class="pi-tagline">{p["tag"]}</p>
    <div class="pi-specs"><h4>Product Specifications</h4>{specs}</div>
    <div class="pi-features"><h4>Key Features</h4><ul>{feats}</ul></div>
    <div class="pi-actions">
      <a href="#quote" class="btn-quote">✝ Request a Free Quote</a>
      <a href="../index.html#products" class="btn-quote-outline">← Back to All Products</a>
    </div>
    <div class="pi-trust">
      <div class="pi-trust-item"><span class="dot"></span>Free Shipping $150+</div>
      <div class="pi-trust-item"><span class="dot"></span>Quality Guaranteed</div>
      <div class="pi-trust-item"><span class="dot"></span>Fast Turnaround</div>
      <div class="pi-trust-item"><span class="dot"></span>Church Specialists</div>
    </div>
  </div>
</div>
<div class="product-desc">
  <div><h2>About This Product</h2>{desc}</div>
  <div class="use-cases"><h4>✝ Perfect For</h4>{uc}</div>
</div>
<section class="quote-section" id="quote">
  <div class="quote-inner">
    <div class="quote-header">
      <h2>Request a Free Quote</h2>
      <p>Fill out the form below and we will get back to you within 1 business day with pricing and options tailored to your ministry.</p>
      <div class="divider"></div>
    </div>
    <div class="quote-form" id="quoteFormWrap">
      <form id="quoteForm" onsubmit="submitQuote(event)">
        <input type="hidden" name="product" value="{p["name"]}"/>
        <div class="form-row">
          <div class="form-group"><label>Full Name *</label><input type="text" name="name" placeholder="Pastor John Smith" required/></div>
          <div class="form-group"><label>Email Address *</label><input type="email" name="email" placeholder="pastor@yourchurch.com" required/></div>
        </div>
        <div class="form-row">
          <div class="form-group"><label>Phone Number</label><input type="tel" name="phone" placeholder="(555) 000-0000"/></div>
          <div class="form-group"><label>Church / Organization</label><input type="text" name="church" placeholder="Grace Community Church"/></div>
        </div>
        <div class="form-row">
          <div class="form-group"><label>Size / Dimensions</label><select name="size"><option value="">Select a size...</option>{sizes}<option value="Custom / Other">Custom / Other</option></select></div>
          <div class="form-group"><label>Quantity Needed</label><select name="quantity"><option value="">Select quantity...</option><option>1</option><option>2-5</option><option>6-10</option><option>11-25</option><option>26-50</option><option>51-100</option><option>100+</option></select></div>
        </div>
        <div class="form-row">
          <div class="form-group"><label>Timeline</label><select name="timeline"><option value="">Select timeline...</option><option>Same day (rush)</option><option>1-3 business days</option><option>1 week</option><option>2 weeks</option><option>1 month or more</option><option>Flexible</option></select></div>
          <div class="form-group"><label>Do you have a design ready?</label><select name="design"><option value="">Select...</option><option>Yes — print-ready artwork</option><option>Partially — I have a logo/assets</option><option>No — I need design help</option><option>I would like to use a template</option></select></div>
        </div>
        <div class="form-group"><label>Additional Details / Notes</label><textarea name="message" placeholder="Tell us anything else — colors, design ideas, specific requirements, event date, etc."></textarea></div>
        <div class="form-check"><input type="checkbox" id="consent" required/><label for="consent">I agree to be contacted by Divine Printing regarding this quote request. We respect your privacy and will never share your information.</label></div>
        <button type="submit" class="btn-submit" id="submitBtn">✝ Send My Quote Request</button>
      </form>
      <div class="form-success" id="formSuccess" style="display:none">
        <div class="success-icon">🙏</div>
        <h3>Quote Request Received!</h3>
        <p>Thank you for reaching out. We will review your request and get back to you within 1 business day.</p>
        <p style="margin-top:12px;font-size:.85rem;color:rgba(255,255,255,.6)">"Whatever you ask in my name, this I will do." — John 14:13</p>
      </div>
    </div>
  </div>
</section>
{FOOTER}
<script>
async function submitQuote(e) {{
  e.preventDefault();
  const btn = document.getElementById('submitBtn');
  btn.textContent = 'Sending...';
  btn.disabled = true;
  const data = new FormData(document.getElementById('quoteForm'));
  try {{
    const res = await fetch('../send-quote.php', {{method:'POST', body:data}});
    const json = await res.json();
    if (json.success) {{
      document.getElementById('quoteForm').style.display = 'none';
      document.getElementById('formSuccess').style.display = 'block';
    }} else {{
      btn.textContent = '✝ Send My Quote Request';
      btn.disabled = false;
      alert(json.message || 'Something went wrong. Please try again.');
    }}
  }} catch(err) {{
    document.getElementById('quoteForm').style.display = 'none';
    document.getElementById('formSuccess').style.display = 'block';
  }}
}}
</script>
</body>
</html>'''

for p in P:
    path = f"{OUT}/{p['s']}.html"
    with open(path, "w") as f:
        f.write(render(p))
    print(f"✓  {p['s']}.html")

print(f"\nDone — {len(P)} pages generated in {OUT}/")
